config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :experiences, only: [:index, :show, :new, :create] do
    resources :bookings, only: [:create]
  end
  resources :bookings, only: [:index, :update]
  namespace :owner do
    resources :bookings, only: [:index]
    resources :experiences, only: [:index, :destroy]
  end
  
  resources :experiences do
    resources :build, controller: 'experiences/build'
  end
end

app/models/experience.rb
class Experience < ApplicationRecord
  belongs_to :user
  has_many_attached :photos # Should 2-4 photos
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  validates :name, presence: true, if: :active_or_name?
  validates :start_time, presence: true, if: :active_or_start?
  validates :end_time, presence: true, if: :active_or_end?
  validates :price, presence: true, if: :active_or_price?
  validates :description, presence: true, if: :active_or_description?
  validates :address, presence: true, if: :active_or_address?
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  # TODO: The seeds don't have proper addresses
  enum status: { building: 'building', add_name: 'add_name', add_description: 'add_description', add_price: 'add_price', add_address: 'add_address', add_photos: 'add_photos', active: 'active' }
  scope :in_progress, -> { !active }
  scope :published, -> { active }

  def duration
    return nil unless end_time && start_time

    (end_time - start_time) / 1.hour
  end

  def start_time_formatted
    start_time.strftime('%l%p')
  end

  def end_time_formatted
    end_time.strftime('%l%p')
  end

  def active_or_name?
    status.include?('name') || active?
  end

  def active_or_start?
    status.include?('start') || active?
  end

  def active_or_end?
    status.include?('end') || active?
  end

  def active_or_description?
    status.include?('description') || active?
  end

  def active_or_price?
    status.include?('price') || active?
  end

  def active_or_address?
    status.include?('address') || active?
  end
end

app/controllers/experiences/build_controller.rb
class Experiences::BuildController < ApplicationController
  include Wicked::Wizard
  skip_before_action :authenticate_user!
  before_action :set_progress, only: [:show]


  steps :add_name, :add_description, :add_price, :add_address, :add_photos

  def show
    @experience = Experience.find(params[:experience_id])
    authorize @experience
    render_wizard
  end


  def update
    @experience = Experience.find(params[:experience_id])
    params[:experience][:status] = step.to_s
    params[:experience][:status] = 'active' if step == steps.last
    authorize @experience
    @experience.update(experience_params)
    render_wizard @experience
  end

  def new
    @experience = Experience.find(params[:experience_id])
    authorize @experience
    redirect_to wizard_path(steps.first)
  end

  def finish_wizard_path
    experience_path(@experience)
  end

  private

  def set_progress
    if wizard_steps.any? && wizard_steps.index(step).present?
      @progress = ((wizard_steps.index(step) + 1).to_d / wizard_steps.count.to_d) * 100
    else
      @progress = 0
    end
  end

  def experience_params
    params.require(:experience).permit(:name, :description, :price, :start_time, :end_time, :address, :status, photos: [])
  end
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @experiences = policy_scope(Experience).includes(:photos_attachments, :photos_blobs).active
    @markers = @experiences.geocoded.map do |experience|
      {
        lat: experience.latitude,
        lng: experience.longitude,
        popup_html: render_to_string(partial: "map_popup", locals: { experience: experience }),
        marker_html: render_to_string(partial: "map_marker", locals: { experience: experience })
      }
    end
  end

  def show
    @experience = Experience.find(params[:id])
    @booking = Booking.new
    authorize @experience
  end

  def new
    @experience = Experience.new
    @experience.user = current_user
    @experience.save
    authorize @experience
    redirect_to new_experience_build_path(@experience)
  end

end

app/controllers/owner/bookings_controller.rb
module Owner
  class BookingsController < ApplicationController
    def index
      @bookings = policy_scope([:owner, Booking]).order(date: :asc)
    end
  end
end

app/controllers/owner/experiences_controller.rb
module Owner
    class ExperiencesController < ApplicationController
      def index
        @experiences = policy_scope([:owner, Experience]).order(created_at: :asc)
      end

      def destroy
        @experience = Experience.find(params[:id])
        authorize @experience
        @experience.destroy
      end
    end
  end
  

app/views/owner/experiences/_in_progress.html.erb
<div class="container px-5">
  <div class="container px-5">
    <div class="d-flex justify-content-between align-items-center py-5">
      <h3>Your pending experiences</h3>
      <%= link_to "Create a new idea", new_experience_path, class: "btn btn-primary" %>
    </div>
    <% experiences.each do |experience| %>
      <div class="border container p-4 bg-white shadow rounded my-3">
        <div class="d-flex justify-content-between">
          <div>
            <div class="d-flex flex-row">
              <span class="border border-right border-warning border-3"></span>
              <small class="border border-start-0 p-1"><strong>In progress</strong></small>
            </div>
            <h4 class="mt-3">Experience</h4>
            <p>You will need a few more details before you can submit it.</p>
          </div>
          <div class="bg-secondary p-3 rounded w-25">
          </div>
        </div>
        <hr>
        <div class="d-flex flex-row ">
          <i class="far fa-paper-plane p-3"></i>
          <p><strong>Finish submitting your experience</strong><br>
            Make sure to complete all the sections to submit your experience</p>
        </div>
        <hr>
        <div class="d-flex flex-row">
          <strong><u><%= link_to "Continue", experience_build_path(experience, :add_name) %></u></strong>
          <strong><u><%= link_to "Delete",  owner_experience_path(experience), method: :delete, class: "px-2" %></u></strong>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/owner/experiences/_published.html.erb
<div class="container px-5">
  <div class="container px-5">
    <div class="d-flex justify-content-between align-items-center py-5">
      <h3>Your published experiences</h3>
      <%= link_to "Create a new idea", new_experience_path, class: "btn btn-primary" %>
    </div>
    <% experiences.each do |experience| %>
      <%= link_to experience_path(experience) do %>
        <div class="border container p-4 bg-white shadow rounded my-3">
          <div class="d-flex justify-content-between">
            <div>
              <div class="d-flex flex-row">
                <span class="border border-right border-success border-3"></span>
                <small class="border border-start-0 p-1"><strong>Published</strong></small>
              </div>
              <h4 class="mt-3"><%= experience.name %></h4>
              <p> <%= experience.description %></p>
            </div>
            <div class="my-experience-card">
              <%= cl_image_tag experience.photos.first&.key %>
            </div>
          </div>
          <hr>
          <div class="d-flex">
            <div class="d-flex flex-row align-items-center pe-5">
              <i class="fas fa-shopping-cart pe-2"></i>
              <p class="pt-3"><strong>Booked:</strong> <%= experience.bookings.size %> times</p>
            </div>
            <div class="d-flex flex-row pe-5 align-items-center">
              <i class="fas fa-user pe-2"></i>
              <p class="pt-3"><strong>Last booked:</strong> <%= experience.bookings.last.created_at.strftime('%b %d') %></p>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/owner/experiences/index.html.erb
<%= content_for :nav do %>
  <ul class="nav" role="tablist">
    <li>
      <button class="btn active" id="upcoming-tab" data-bs-toggle="pill" data-bs-target="#upcoming" type="button" role="tab" aria-controls="upcoming" aria-selected="true">
        Published
        <% if @experiences.active.any? %>
          <span class="ms-1 badge rounded-pill bg-dark"><%= @experiences.active.size %></span>
        <% end %>
      </button>
    </li>
    <li>
      <button class="btn d-flex align-items-center" id="pending-tab" data-bs-toggle="pill" data-bs-target="#pending" type="button" role="tab" aria-controls="pending" aria-selected="false">
        In progress
        <% if @experiences.in_progress.any? %>
          <span class="ms-1 badge rounded-pill bg-dark"><%= @experiences.in_progress.size %></span>
        <% end %>
      </button>
    </li>
  </ul>
<% end %>
<div class="container py-4">
  <div class="tab-content">
    <div class="tab-pane fade show active" id="upcoming" role="tabpanel" aria-labelledby="upcoming-tab">
      <%= render 'published', experiences: @experiences.active %>
    </div>
    <div class="tab-pane fade" id="pending" role="tabpanel" aria-labelledby="pending-tab">
      <%= render 'in_progress', experiences: @experiences.in_progress %>
    </div>
  </div>
</div>