config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :experiences, only: [:index, :show, :new, :create] do
    resources :bookings, only: [:create]
  end
  resources :bookings, only: [:index, :update]
  namespace :owner do
    resources :bookings, only: [:index]
    resources :experiences, only: [:index, :destroy]
  end
  
  resources :experiences do
    resources :build, controller: 'experiences/build'
  end
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :experience
  validates :date, presence: true
  validates :participants, numericality: { only_integer: true, greater_than: 0 }
  enum status: { pending: 0, accepted: 1, rejected: 2 }

  scope :past, -> { where('date < ?', Date.today) }
  scope :future, -> { where('date > ?', Date.today) }
  scope :today, -> { accepted.where(date: Date.today) }
  scope :upcoming, -> { accepted.future }
  scope :need_response, -> { pending.future }
  scope :expired, -> { pending.past }
  scope :completed, -> { accepted.past }
  scope :not_rejected, -> { where.not(status: :rejected) }

  def price
    experience.price * participants
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = policy_scope(Booking).order(:date)
  end

  def create
    @experience = Experience.find(params[:experience_id])
    @booking = Booking.new(booking_params)
    @booking.experience = @experience
    @booking.user = current_user
    authorize @booking
    if @booking.save
      redirect_to bookings_path
    else
      render 'experiences/show'
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:date, :participants, :status)
  end
end

app/controllers/owner/bookings_controller.rb
module Owner
  class BookingsController < ApplicationController
    def index
      @bookings = policy_scope([:owner, Booking]).order(date: :asc)
    end
  end
end

app/views/bookings/_booking.html.erb
<% if local_assigns[:thumbnail] %>
  <%= render 'thumbnail', booking: booking %>
<% else %>
  <div class="card booking-card mt-4 shadow position-relative">
    <div class="card-image-top position-relative h-18 overflow-hidden">
      <%= render 'experiences/photo_gallery', photos: booking.experience.photos %>
      <div class="position-absolute top-0 start-0 bg-black w-100 h-100 opacity-50 rounded">
      </div>
      <div class="booking-card--img-text position-absolute translate-middle top-50 start-50 text-white">
        <p class="booking-card--date fw-normal"><%= booking.date.strftime('%b %d, %Y') %> · <span class="fw-light"><%= booking.experience.start_time_formatted %> - <%= booking.experience.end_time_formatted %></span></p>
        <h3 class="text-center m-0"><%= booking.experience.name %></h3>
        <p class="text-center m-0 opacity-80">Guided by <%= booking.experience.user.first_name %></p>
      </div>
    </div>
    <div class="card-body">
      <div class="container">
        <div class="row">
          <div class="col-md-6 order-md-2">
            <p class="fs-5 fw-normal text-end m-0"><%= currency(booking.price) %></p>
          </div>
          <div class="col-md-6 order-md-1">
            <div class="d-flex">
              <%= render 'avatar', user: booking.experience.user, large: true %>
              <div class="ms-3">
                <h5>Your guide, <%= booking.experience.user.first_name %></h5>
                <small>Guiding near-death experiences since <%= booking.experience.user.created_at.year %></small>
              </div>
            </div>
          </div>
        </div>
        <div class="row gy-3 mt-2">
          <div class="col-md-8 pe-5">
            <h6>What you'll do:</h6>
            <p class="ps-3 border-start border-5 m-0">
              <%= booking.experience.description %>
            </p>
          </div>
          <div class="col-md-4">
            <small>
              <p class="m-1"><i class="far fa-calendar-check w-2"></i>
                <%= booking.date.strftime('%b %d, %Y') %> from <%= booking.experience.start_time_formatted %> to <%= booking.experience.end_time_formatted %>
              </p>
              <p class="m-1"><i class="far fa-user w-2"></i>
                <%= pluralize(booking.participants, 'participants') %>
              </p>
              <p class="m-1"><i class="far fa-compass w-2"></i>
                <% coords = [booking.experience.latitude, booking.experience.longitude].join(',') %><%= link_to 'Get directions', "https://www.google.com/maps/search/?api=1&query=#{coords}", target: :blank %>
              </p>
            </small>
          </div>
        </div>
      </div>
    </div>
    <p class="position-absolute top-0 start-0 ms-2 mt-1">
      <%= booking_status_badge(booking) %>
    </p>
  </div>
<% end %>

app/views/bookings/_modal.html.erb
<div class="modal fade" id="bookingModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" data-booking-picker-target="modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Confirmation</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body pt-1" data-controller='price-update'>
        <%= simple_form_for [@experience, @booking] do |f| %>
          <%= f.input :date, as: :string, label: false, placeholder: "Choose your date...", input_html: { class: "datepicker" } %>
          <%= f.input :participants, input_html: { value: 1, min: 1, max: 10, data: { action: "change->price-update#update", price: @experience.price } } %>
          <div class="d-flex justify-content-between align-items-baseline mt-3">
            <div class="d-flex align-items-baseline">
              <h4 class="lh-lg mb-1 me-1" >¥<span data-price-update-target='price'><%= number_with_delimiter(@experience.price) %> </span></h4>
              <p class="lh-lg fw-lighter mb-2"> total</p>
            </div>
            <small class="text-muted"><%= @experience.start_time_formatted %> - <%= @experience.end_time_formatted %></small>
          </div>
          <div class="modal-footer mt-2">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <%= f.button :submit, "Request Booking", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/_new.html.erb
<div class="new-booking-card" data-controller="booking-picker">
  <div class="d-flex align-items-baseline">
    <h4 class="lh-lg mb-1">From ¥<%= number_with_delimiter(@experience.price) %></h4>
    <p class="lh-lg fw-lighter mb-2"> / person</p>
  </div>
  <small class="text-muted"><u>Show all prices</u></small>
  <%= text_field_tag :date, nil, placeholder: "Choose your date...", class: "datepicker form-control" %>
  <% [Date.today, Date.tomorrow, Date.tomorrow + 1].each_with_index do |day, index| %>
    <div class="row py-3 align-items-center <%= 'border-top' unless index.zero? %>" data-booking-picker-target="<%= index.zero? ? 'template' : 'extra' %>">
      <div class="col-6">
        <small><strong id="booking-date-holder"><%= day.to_s(:long) %></strong></small><br>
        <small class="text-muted"><%= @experience.start_time_formatted %> - <%= @experience.end_time_formatted %></small>
      </div>
      <div class="col-6 text-end">
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#bookingModal" data-date="<%= day.to_s %>" data-action="click->booking-picker#fillModalForm">
          Choose
        </button>
      </div>
    </div>
  <% end %>
  <%= render 'bookings/modal' %>
</div>

app/views/bookings/_no_bookings.html.erb
<div class="card flex-row overflow-hidden">
  <div class="card-body px-5 py-3 w-40p my-auto">
    <i class="fas fa-couch fa-2x text-primary mb-2"></i>
    <h6 class="card-title">You have no experiences booked... yet!</h6>
    <p class="card-text"><small>Time to step out of your comfort zone and to start feeling alive again</small></p>
    <%= link_to 'Start searching', experiences_path, class: 'btn btn-primary' %>
  </div>
  <%= image_tag 'tightrope.jpg', class: 'card-img-left w-60p h-16 fit-cover', style: 'object-position: 50% 60%;' %>
</div>

app/views/bookings/_thumbnail.html.erb
<%= link_to experience_path(booking.experience) do %>
  <%# Linking to the experience since there is no bookings#show %>
  <div class="booking-thumbnail d-flex">
    <%= cl_image_tag booking.experience.photos.first.key, width: 80, height: 80, class: 'fit-cover rounded' %>
    <div class="my-auto ps-3">
      <h6><%= booking.experience.name %></h6>
      <p class="m-0"><%= booking.date.strftime('%b %d, %Y') %> · Guided by <%= booking.experience.user.first_name %></p>
    </div>
  </div>
<% end %>

app/views/bookings/index.html.erb
<div class="container py-4">
  <div class="row">
    <div class="col">
      <%# Upcoming bookings %>
      <h2 class="mt-5 mb-4">Your next experiences</h2>
      <% if @bookings.future.not_rejected.any? %>
        <p>Get your affairs in order, and prepare for your next <%= 'experience'.pluralize(@bookings.future.count) %>...</p>
        <%= render @bookings.future.not_rejected %>
      <% else %>
        <%= render 'no_bookings' %>
      <% end %>
      <%# Past bookings %>
      <h4 class="mt-5">Experiences you've survived</h4>
      <% if @bookings.completed.any? %>
        <div class="grid-3-cols mt-4">
          <%= render @bookings.completed, thumbnail: true %>
        </div>
      <% else %>
        <p>You have no past experiences yet.</p>
      <% end %>
      <% if @bookings.rejected.any? %>
        <%# Rejected - should we show them? %>
        <h4 class="mt-5">Rejected</h4>
        <div class="grid-3-cols mt-4">
          <%= render @bookings.rejected, thumbnail: true %>
        </div>
      <% end %>
    </div>
  </div>
</div>