config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :experiences, only: [:index, :show, :new, :create] do
    resources :bookings, only: [:create]
  end
  resources :bookings, only: [:index, :update]
  namespace :owner do
    resources :bookings, only: [:index]
    resources :experiences, only: [:index, :destroy]
  end
  
  resources :experiences do
    resources :build, controller: 'experiences/build'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def currency(amount)
    number_to_currency(amount, { unit: '¥', precision: 0 })
  end

  def booking_status_badge(booking)
    if booking.date < Date.today
      label = { pending: 'Expired', accepted: 'Completed', rejected: 'Rejected' }[booking.status.to_sym]
      color = { pending: 'secondary', accepted: 'primary', rejected: 'secondary' }[booking.status.to_sym]
    elsif booking.user == current_user
      label = { pending: 'Awaiting confirmation', accepted: 'Confirmed', rejected: 'Rejected' }[booking.status.to_sym]
      color = { pending: 'warning', accepted: 'primary', rejected: 'secondary' }[booking.status.to_sym]
    else
      label = { pending: 'Request', accepted: 'Confirmed', rejected: 'Rejected' }[booking.status.to_sym]
      color = { pending: 'primary', accepted: 'primary', rejected: 'secondary' }[booking.status.to_sym]
    end
    tag.span(label, class: "me-2 badge bg-#{color}")
  end

  def format_float(num)
    number_with_precision(num, strip_insignificant_zeros: true)
  end
end

app/views/application/_avatar.html.erb
<%= image_tag user.photo.attached? ? cl_image_path(user.photo.key) : 'default_avatar.jpg',
              alt: :avatar,
              class: "avatar #{class_names(
                'avatar-large': local_assigns[:large],
                'avatar-bordered': local_assigns[:border],
                'avatar-square': local_assigns[:square])
              }"
%>

app/views/application/_flashes.html.erb
<% if notice %>
  <div class="alert alert-light alert-dismissible d-flex align-items-center fade show" role="alert">
    <i class="far fa-check-circle text-primary me-2"></i>
    <div>
      <%= notice %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-light alert-dismissible d-flex align-items-center fade show" role="alert">
    <i class="fas fa-exclamation-triangle text-danger me-2"></i>
    <div>
      <%= alert %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  </div>
<% end %>

app/views/application/_map_marker.html.erb
<div class="map-marker">
  <span class="price-tag"><%= currency(experience.price) %></span>
</div>

app/views/application/_map_popup.html.erb
<div class="map-popup shadow">
  <div class="photo-grid grid-<%= pluralize(experience.photos.first(3).length, 'photo').split(' ').join('-') %>">
    <% experience.photos.first(3).each do |photo| %>
      <div class="photo">
        <%= cl_image_tag photo.key, alttext: experience.name, width: 330, height: 330, crop: :fill, gravity: :faces %>
      </div>
    <% end %>
  </div>
  <div class="p-3">
    <%# TODO: make rating dynamic %>
    <p><i class="fas fa-star text-primary"></i> <span class="fw-bold">4.67</span> (722)</p>
    <p><%= experience.name %></p>
    <p class="mb-0"><span class="fw-bold">From <%= number_to_currency(experience.price, {unit: '¥', precision: 0}) %></span> / hour</p>
  </div>
</div>

app/views/application/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top <%= class_names transparent: local_assigns[:transparent], dark: local_assigns[:dark] %>">
  <div class="container-fluid d-flex justify-content-between position-relative">
    <%= link_to root_path, class: "navbar-brand" do %>
      <i class="ms-3 fas fa-skull-crossbones text-primary"></i>
    <% end %>
    <div class="additional-nav">
      <%= content_for(:nav) %>
    </div>
    <div class="justify-content-end" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item px-2">
          <%= link_to "Browse experiences", experiences_path, class: "nav-link" %>
        </li>
        <li class="nav-item px-2">
          <% if !current_user&.owner? %>
            <%= link_to "Become a guide", new_experience_path, class: "nav-link" %>
          <% end %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item dropdown dropstart ps-2">
            <%= content_tag :div, id: "navbarDropdownMenuLink", data: { "bs-toggle": "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false, role: "button", class: "d-flex align-items-center" do %>
              <i class="fas fa-bars me-2"></i>
              <%= render 'avatar', user: current_user, border: true %>
            <% end %>
            <ul class="dropdown-menu shadow-lg fw-lighter" aria-labelledby="navbarDropdownMenuLink">
              <li><%= link_to "Messages", nil, class: "dropdown-item fw-normal" %></li>
              <li><%= link_to "View bookings", bookings_path, class: "dropdown-item fw-normal" %></li>
              <li><%= link_to "View wishlist", nil, class: "dropdown-item fw-normal" %></li>
              <li><%= link_to "Manage profile", nil, class: "dropdown-item fw-normal" %></li>
              <hr>
              <li><%= link_to "Guide an experience", new_experience_path, class: "dropdown-item" %></li>
              <% if current_user.owner? %>
                <li><%= link_to "Manage experiences", owner_experiences_path, class: "dropdown-item" %></li>
                <li>
                  <%= link_to owner_bookings_path, class: "dropdown-item d-flex align-items-center" do %>
                    Manage reservations
                    <% if current_user.bookings_as_owner.pending.any? %>
                      <span class="badge rounded-pill bg-danger ms-1">
                        <%= current_user.bookings_as_owner.pending.size %>
                      </span>
                    <% end %>
                  <% end %>
                </li>
              <% end %>
              <hr>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item px-2">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/application/_search_bar.html.erb
<%= form_tag experiences_path, method: :get, class: "search-form-control" do %>
  <div class="form-group">
    <%= text_field :query, nil,
                   value: params[:query],
                   class: "form-control string required rounded-pill",
                   placeholder: "" %>
    <button name="button" type="submit" class="btn btn-primary rounded-circle">
      <i class="fas fa-search"></i>
    </button>
  </div>
<% end %>